apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: ibm-spectrum-scale
  app.kubernetes.io/name: operator

namespace: ibm-spectrum-scale-operator
namePrefix: ibm-spectrum-scale-

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

images:
- digest: sha256:3979c40e5d70905aa10ec321c69dfbe7b1cedaf884483b7321bf916c386b6e0b
  name: controller
  newName: icr.io/cpopen/ibm-spectrum-scale-operator

components:
- ../../components/rbac/deploy
- ../../components/rbac/regionaldr
- ../../components/rbac/gui
- ../../components/webhook/deploy
- ../../components/manager/deploy
