---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: regional-dr
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    resourceNames: 
    - stunnel
    verbs:
    - get