---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: regional-dr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: regional-dr
subjects:
  - kind: ServiceAccount
    name: ibm-spectrum-scale-regional-dr
    namespace: ibm-spectrum-scale-operator