---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
imagePullSecrets:
  # TODO: ibm-spectrum-scale- will get double added if a user creates a secrets directory. We need to handle this better probably
  - name: ibm-spectrum-scale-registrykey
  - name: ibm-entitlement-key
automountServiceAccountToken: false
