---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: regional-dr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: regional-dr
subjects:
  - kind: ServiceAccount
    name: regional-dr