---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: regional-dr
rules:
  - apiGroups:
      - scale.spectrum.ibm.com
    resources:
      - asyncreplications
      - consistencygroups
      - regionaldrs
    verbs:
      - get
      - list
      - watch