---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: veviction.scale.spectrum.ibm.com
  # namespaceSelector isn't part of kubebuilder supported options
  # use a merge patch to add the namespaceSelector
  namespaceSelector: 
    matchExpressions:
    # note: this label is also used for other scale namespaces like coredns ns
    - key: app.kubernetes.io/part-of
      operator: In
      values:
        - ibm-spectrum-scale