# This patch add annotation to admission webhook config and
# the variables $(CERTIFICATE_NAMESPACE) and $(CERTIFICATE_NAME) will be substituted by kustomize.
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    #cert-manager.io/inject-ca-from: ibm-spectrum-scale-operator/ibm-spectrum-scale-selfsigned-issuer
    service.beta.openshift.io/inject-cabundle: "true"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    #cert-manager.io/inject-ca-from: ibm-spectrum-scale-operator/ibm-spectrum-scale-selfsigned-issuer
    service.beta.openshift.io/inject-cabundle: "true"
