# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/scale.spectrum.ibm.com_clusters.yaml
  - bases/scale.spectrum.ibm.com_daemons.yaml
  - bases/scale.spectrum.ibm.com_callhomes.yaml
  - bases/scale.spectrum.ibm.com_remoteclusters.yaml
  - bases/scale.spectrum.ibm.com_filesystems.yaml
  - bases/scale.spectrum.ibm.com_guis.yaml
  - bases/scale.spectrum.ibm.com_encryptionconfigs.yaml
  - bases/scale.spectrum.ibm.com_pmcollectors.yaml
  - bases/scale.spectrum.ibm.com_recoverygroups.yaml
  - bases/scale.spectrum.ibm.com_grafanabridges.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_clusters.yaml
#- patches/webhook_in_daemons.yaml
#- patches/webhook_in_callhomes.yaml
#- patches/webhook_in_remoteclusters.yaml
#- patches/webhook_in_filesystems.yaml
#- patches/webhook_in_guis.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_clusters.yaml
#- patches/cainjection_in_daemons.yaml
#- patches/cainjection_in_callhomes.yaml
#- patches/cainjection_in_remoteclusters.yaml
#- patches/cainjection_in_filesystems.yaml
#- patches/cainjection_in_guis.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
