resources:
- manager.yaml

patchesStrategicMerge:
- manager_config_patch.yaml
- manager_webhook_patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3f6e90c08d232338bc21127805a285c7debdbf5cec512ef84de9899a700c438e
  name: controller
  newName: icr.io/cpopen/ibm-spectrum-scale-operator
