resources:
- manager.yaml

patchesStrategicMerge:
- manager_config_patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:95be2ad7696f0a5e864c0116f177c8887131c438b31d45255379644dbf88a33b
  name: controller
  newName: icr.io/cpopen/ibm-spectrum-scale-operator
