resources:
- manager.yaml

patchesStrategicMerge:
- manager_config_patch.yaml
- manager_webhook_patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:fcc14fae885ca862b9ed8a61544dcea3c7b8f3a9d4d691539375bc6d20016370
  name: controller
  newName: icr.io/cpopen/ibm-spectrum-scale-operator
