resources:
- manager.yaml

patchesStrategicMerge:
- manager_config_patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:90abc5815743e2ed306907f33a002467d021fd0883a1ae7e0e9b4992871e4a0e
  name: controller
  newName: icr.io/cpopen/ibm-spectrum-scale-operator
