apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - "--config=controller_manager_config.yaml"
            - "--zap-log-level=1"
          volumeMounts:
            - name: manager-config
              mountPath: /controller_manager_config.yaml
              subPath: controller_manager_config.yaml
            - name: cabundle
              mountPath: /etc/ssl/service
      volumes:
        - name: manager-config
          configMap:
            name: manager-config
        - name: cabundle
          configMap:
           name: "ibm-spectrum-scale-cabundle"
           optional: true
