apiVersion: v1
kind: Namespace
metadata:
  name: ibm-spectrum-scale
  annotations:
    openshift.io/node-selector: ""
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    # OCP attempts to map SCC's to pod security labels, but
    # cannot handle direct pod creations. We don't have a role binding
    # for privileged in this namespace and thus OCP will not mutate
    # our enforcement level to a high enough privilege.
    security.openshift.io/scc.podSecurityLabelSync: "false"
