apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysmon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sysmon
subjects:
  - kind: ServiceAccount
    name: core
