apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-spectrum-scale-privileged
subjects:
  - kind: ServiceAccount
    name: pmcollector
  - kind: ServiceAccount
    name: gui
