# permissions for end users to edit encryptionconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: encryptionconfig-editor-role
rules:
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - encryptionconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - encryptionconfigs/status
  verbs:
  - get
