resources:
  - role.yaml
  - role_binding.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - manager_service_account.yaml
  - privileged_operator_role_binding.yaml
  - privileged_role.yaml
  - privileged_security_context_constraint.yaml
  - restricted_role.yaml
  - restricted_security_context_constraint.yaml
  - gui_role.yaml
  # Comment the following 4 lines if you want to disable
  # the auth proxy (https://github.com/brancz/kube-rbac-proxy)
  # which protects your /metrics endpoint.
  # - auth_proxy_service.yaml
  # - auth_proxy_role.yaml
  # - auth_proxy_role_binding.yaml
  # - auth_proxy_client_clusterrole.yaml

configurations:
  - kustomizeconfig.yaml
