---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: system
imagePullSecrets:
# TODO: ibm-spectrum-scale- will get double added if a user creates a secrets directory. We need to handle this better probably
  - name: ibm-spectrum-scale-registrykey
