apiVersion: scale.spectrum.ibm.com/v1beta1
kind: Filesystem
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: local-sample
  namespace: ibm-spectrum-scale
spec:
  local:
    blockSize: 4M
    pools:
    - disks:
      - disk0
      - disk1
      - disk2
      name: system
    replication: 1-way
    type: shared
  seLinuxOptions: {}
