---
apiVersion: scale.spectrum.ibm.com/v1beta1
kind: Cluster
metadata:
  name: ibm-spectrum-scale
spec:
  daemon:
    nodeSelector:
      node-role.kubernetes.io/worker: ""
    roles:
    - name: client
      resources:
        memory: 4Gi
