---
apiVersion: scale.spectrum.ibm.com/v1beta1
kind: Filesystem
metadata:
  name: remote-sample
spec:
  remote:
    cluster: remotecluster-sample
    fs: fs1
  seLinuxOptions:
    level: s0
    role: object_r
    type: container_file_t
    user: system_u
