---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 02-worker-ibm-spectrum-scale-s390x-vmalloc 
spec:
  kernelArguments:
    - 'vmalloc=4096G'
