namespace: ibm-spectrum-scale

commonLabels:
  app.kubernetes.io/instance: ibm-spectrum-scale
  app.kubernetes.io/name: cluster

resources:
  - scale_v1beta1_filesystem_remote.yaml
  - scale_v1beta1_remotecluster.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
