---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "worker"
  name: 00-worker-ibm-spectrum-scale-kernel-devel
spec:
  config:
    ignition:
      version: 3.2.0
  extensions:
     - kernel-devel

