---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-spectrum-scale-core
roleRef:
  kind: Role
  name: ibm-spectrum-scale-core
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ibm-spectrum-scale-core
