apiVersion: scale.spectrum.ibm.com/v1beta1
kind: EncryptionConfig
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: encryption-config-sample
  namespace: ibm-spectrum-scale
spec:
  backupServers:
  - keyserver1.example.com
  - keyserver2.example.com
  - keyserver3.example.com
  - keyserver4.example.com
  - keyserver5.example.com
  cacert: sample-ca-cert
  client: sampleClient
  port: 9443
  remoteRKM: sampleRKM
  secret: keyserver-credentials
  server: keyserver.example.com
  tenant: sampleTenant
