apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd/scale.spectrum.ibm.com_compressionjobs.yaml
- crd/scale.spectrum.ibm.com_diskjobs.yaml
- crd/scale.spectrum.ibm.com_dnsconfigs.yaml
- crd/scale.spectrum.ibm.com_dnss.yaml
- crd/scale.spectrum.ibm.com_networkpolicies.yaml
- crd/scale.spectrum.ibm.com_restripefsjobs.yaml
- crd/scale.spectrum.ibm.com_stretchclusterinitnodes.yaml
- crd/scale.spectrum.ibm.com_stretchclusters.yaml
- crd/scale.spectrum.ibm.com_stretchclustertiebreakers.yaml
- crd/scale.spectrum.ibm.com_upgradeapprovals.yaml
- crd/scale.spectrum.ibm.com_asyncreplications.yaml
- crd/scale.spectrum.ibm.com_clusterinterconnects.yaml
- crd/scale.spectrum.ibm.com_consistencygroups.yaml
- crd/scale.spectrum.ibm.com_regionaldrexports.yaml
- crd/scale.spectrum.ibm.com_approvalrequests.yaml
  # +kubebuilder:scaffold:crdkustomizeresource

configurations:
- kustomizeconfig.yaml
