apiVersion: v1
data:
  buildgpl: |
    #!/bin/sh
    mmbuildgpl
  hostPathDirectories: |
    /usr/src/kernels
    /usr/include/asm
    /usr/include/asm-generic
    /usr/include/linux
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: buildgpl
  namespace: ibm-spectrum-scale
