apiVersion: v1
data:
  buildgpl: |
    #!/bin/bash
    #
    # When using NVIDIA Network Operator to deploy MOFED drivers in a Kubernetes environment,
    # any restart of the MOFED pods will potentially cause the drivers to rebuild. When the build completes
    # the MOFED pod will unload the old and load the new driver.
    #
    # The IBM Storage Scale container native core pods need to wait until the driver build is complete
    # before started the daemon so that none of the RDMA libraries are invoked, causing issues with the
    # unload of the kernel mod.
    #
    # This script will wait for the driver to indicate ready before starting the core pod
    #
    ELAPSED=0
    SLEEP_INTERVAL=10
    MAX_WAIT=600
    TARGET_DIR=/run/mellanox/drivers
    TARGET_FILE="${TARGET_DIR}/.driver-ready"

    echo "Detected MOFED drivers are in use, waiting $MAX_WAIT seconds for driver to complete building . . ."
    while [ "$ELAPSED" -lt "$MAX_WAIT" ]; do
        if [ -f "$TARGET_FILE" ]; then
            echo "File found!"
            ls -ltr "$TARGET_FILE"
            break
        fi
        sleep "$SLEEP_INTERVAL"
        ELAPSED=$((ELAPSED + SLEEP_INTERVAL))
        echo ". . . waited ${ELAPSED} seconds . . ."
    done

    # Adjust ELAPSED if kernel modules are taking longer to build than expected
    if [ "$ELAPSED" -ge "$MAX_WAIT" ]; then
        echo "After $ELAPSED seconds, unable to detect if MOFED driver is ready. Exiting."
        exit 1
    fi

    # Base image didn't contains these directory
    # Needed for make gpfs on ubuntu system
    # The packages gcc-$(uname -m)-linux-gnu and build-essential must be installed on each node.

    # get the kernel version
    kversion=$(uname -r)
    echo "Kernel version: $kversion"
    currentkernel=$(uname -r | cut -d'-' -f1)
    targetkernel="6.8.0"
    echo "Current base kernel version: $currentkernel"
    echo "Target base kernel version: $targetkernel"

    # check kernel release
    if [ "$(printf '%s\n' "$currentkernel" "$targetkernel" | sort -V | head -n1)" = "$currentkernel" ] \
        && [ "$currentkernel" != "$targetkernel" ]; then
        # for ubuntu 22.04
        # we may able to use this support if change to redhat 10 based image
        echo "Process mmbuildgpl on Ubuntu version 22.04 or earlier."
        kversion=$(uname -r)
        ln -s -T /host/usr/src/linux-headers-$kversion /usr/src/kernels/$kversion
        cp -rf /host/lib/modules/$kversion /lib/modules/$kversion

        # build config/mk.env
        cd /usr/lpp/mmfs/src/
        config/configure linuxdistribution=UBUNTU_LINUX

        # mmbuildgpl
        make World
        make InstallImages
    else
        # for ubuntu 24.04
        echo "Process mmbuildgpl on Ubuntu version 24.04 or newer."
        mkdir -p /usr/src/kernels
        for dir in /host/usr/src/linux-*${kversion%-*}*; do
            if [ -d "$dir" ]; then
                echo "Copying directories: $dir to /usr/src/kernels"
                rsync -a "$dir" "/usr/src/kernels/"
            fi
        done

        # create chroot dir
        chroot_dir="/opt/chroot"
        mkdir -p "$chroot_dir"

        # rsync /host/usr and etc to chroot
        rsync_dirs=("/host/usr" "/host/etc" "/bin")
        for dir in "${rsync_dirs[@]}"; do
            rsync -a $dir "$chroot_dir"
        done
        rsync -a "/usr/src/kernels" "$chroot_dir/usr/src"
        rsync -a "/usr/lpp" "$chroot_dir/usr"

        # create symlinks for lib and lib64 inside of chroot
        cd "$chroot_dir"
        ln -sfn usr/lib "$chroot_dir/lib"
        ln -sfn usr/lib64 "$chroot_dir/lib64"

        # mounting virtual filesystem
        mount_dirs=("/dev" "/proc" "/sys")
        for mnt in "${mount_dirs[@]}"; do
            mkdir -p "$chroot_dir$mnt"
            mount --bind "/host$mnt" "$chroot_dir$mnt"
        done

        # entering chroot
        chroot "$chroot_dir" /bin/bash -c "
        cd /usr/lpp/mmfs/src
        if [[ ! -f /usr/bin/gcc ]]; then
            echo "KERNEL_CC=/usr/bin/`uname -m`-linux-gnu-gcc-13" >> /usr/lpp/mmfs/src/config/site.mk
        else
            echo "KERNEL_CC=/usr/bin/gcc" >> /usr/lpp/mmfs/src/config/site.mk
        fi

        config/configure linuxdistribution=UBUNTU_LINUX
        make World
        make InstallImages "

        # clean up and unmount
        for mnt in "${mount_dirs[@]}"; do
            umount "$chroot_dir$mnt"
        done

        # get the modules from chroot
        kversion=$(uname -r)
        rm -rf /lib/modules/$kversion
        rsync -av /opt/chroot/usr/lib/modules/$kversion /lib/modules
        cp -rf /opt/chroot/usr/lpp/mmfs/bin/lxtrace-$kversion /usr/lpp/mmfs/bin/

        # load the module
        depmod -A
        modprobe tracedev
        modprobe mmfslinux
        modprobe mmfs26

        # checking if modules are available
        if lsmod | grep mmfs; then
            echo "GPFS modules are loaded"
        else
            echo "GPFS modules are not loaded"
        fi
    fi
  hostPathDirectories: |
    /run/mellanox/drivers
    /
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: buildgpl
  namespace: ibm-spectrum-scale
