apiVersion: v1
data:
  buildgpl: |
    #!/bin/bash
    #
    # When using NVIDIA Network Operator to deploy MOFED drivers in a Kubernetes environment,
    # any restart of the MOFED pods will potentially cause the drivers to rebuild. When the build completes
    # the MOFED pod will unload the old and load the new driver.
    #
    # The IBM Storage Scale container native core pods need to wait until the driver build is complete
    # before started the daemon so that none of the RDMA libraries are invoked, causing issues with the
    # unload of the kernel mod.
    #
    # This script will wait for the driver to indicate ready before starting the core pod
    #
    ELAPSED=0
    SLEEP_INTERVAL=10
    MAX_WAIT=600
    TARGET_DIR=/run/mellanox/drivers
    TARGET_FILE="${TARGET_DIR}/.driver-ready"

    echo "Detected MOFED drivers are in use, waiting $MAX_WAIT seconds for driver to complete building . . ."
    while [ "$ELAPSED" -lt "$MAX_WAIT" ]; do
        if [ -f "$TARGET_FILE" ]; then
            echo "File found!"
            ls -ltr "$TARGET_FILE"
            break
        fi
        sleep "$SLEEP_INTERVAL"
        ELAPSED=$((ELAPSED + SLEEP_INTERVAL))
        echo ". . . waited ${ELAPSED} seconds . . ."
    done

    # Adjust ELAPSED if kernel modules are taking longer to build than expected
    if [ "$ELAPSED" -ge "$MAX_WAIT" ]; then
        echo "After $ELAPSED seconds, unable to detect if MOFED driver is ready. Exiting."
        exit 1
    fi
    #
    # Custom the buildgpl
    # Run buildgpl if host and container kernel is different
    #

    # Function for error message
    error_exit() {
        echo "ERROR: $1" 1>&2
        exit 1
    }

    # The required directories and files needs for Ubuntu installation
    prepare_ubuntu_pkgs_installation() {
        echo "Prepare config and env for install ubuntu packages"
        # set up DNS
        rm -rf $CHROOT_PATH/etc/resolv.conf
        cp -f /host/run/systemd/resolve/resolv.conf $CHROOT_PATH/etc/resolv.conf
        # Ensure critical directories exist
        mkdir -p $CHROOT_PATH/var/lib/apt/lists/partial
        mkdir -p $CHROOT_PATH/var/cache/apt/archives/partial
        mkdir -p "$CHROOT_PATH/var/log"
        # Set tmp directory permissions
        mkdir -p "$CHROOT_PATH/tmp" "$CHROOT_PATH/var/tmp"
        chmod 1777 "$CHROOT_PATH/tmp" "$CHROOT_PATH/var/tmp"
        # Initialize dpkg status
        mkdir -p "$CHROOT_PATH/var/lib/dpkg"
        touch "$CHROOT_PATH/var/lib/dpkg/status"
        # Add dummy start-stop-daemon to bypass dpkg post-install scripts
        mkdir -p "$CHROOT_PATH/sbin"
        echo -e '#!/bin/sh\nexit 0' > "$CHROOT_PATH/sbin/start-stop-daemon"
        chmod +x "$CHROOT_PATH/sbin/start-stop-daemon"
        # Mount dev/pts
        mkdir -p "$CHROOT_PATH/dev/pts"
        mount --bind /host/dev/pts "$CHROOT_PATH/dev/pts"
        # Add the dummy initramfs hook
        mkdir -p "$CHROOT_PATH/etc/kernel/postinst.d"
        echo -e '#!/bin/sh\nexit 0' > "$CHROOT_PATH/etc/kernel/postinst.d/initramfs-tools"
        chmod +x "$CHROOT_PATH/etc/kernel/postinst.d/initramfs-tools"
    }

    # Required files
    HOST_PATH="/host"
    OS_FILE="/etc/os-release"
    HOST_OS_FILE="$HOST_PATH/$OS_FILE"
    CONTAINER_OS_FILE=$OS_FILE
    CHROOT_PATH="/opt/chroot"

    # Validate required files
    [[ -d "$HOST_PATH" ]] || error_exit "Host Path is not mounted: $HOST_PATH"
    [[ -f "$HOST_OS_FILE" ]] || error_exit "Host OS file not found: $HOST_OS_FILE"
    [[ -f "$CONTAINER_OS_FILE" ]] || error_exit "Container OS file not found: $CONTAINER_OS_FILE"

    # Extract ID and VERSION_ID from both os-release files
    HOST_ID=$(grep '^ID=' "$HOST_OS_FILE" | cut -d= -f2 | tr -d '"')
    HOST_VER=$(grep '^VERSION_ID=' "$HOST_OS_FILE" | cut -d= -f2 | tr -d '"')
    CONTAINER_ID=$(grep '^ID=' "$CONTAINER_OS_FILE" | cut -d= -f2 | tr -d '"')
    CONTAINER_VER=$(grep '^VERSION_ID=' "$CONTAINER_OS_FILE" | cut -d= -f2 | tr -d '"')

    # Derive major version (split by '.')
    HOST_MAJOR="${HOST_VER%%.*}"
    CONTAINER_MAJOR="${CONTAINER_VER%%.*}"
    echo "Host OS: $HOST_ID $HOST_VER"
    echo "Container OS: $CONTAINER_ID $CONTAINER_VER"

    # checking if gpfs modules are already build from pvc volume mount
    kversion=$(uname -r)
    karch=$(uname -m)
    mmfsdsha=$(sha224sum /usr/lpp/mmfs/bin/mmfsd | cut -d " " -f 1)
    modulesdir="/var/mmfs/gpfsmodules/$kversion/$karch/$mmfsdsha"
    if [[ -d "/var/mmfs/gpfsmodules" ]]; then
        if [[ -d "$modulesdir" ]]; then
            # wait for other node to do the build, but timeout after 10 minutes
            echo "wait for other node to do the build"
            loops=1
            maxloops=20
            while [[ -f "$modulesdir/building" && $loops -le $maxloops ]]; do
                sleep 30
                loops=$((loops + 1))
            done
            gpfsmodextra="$modulesdir/lib/modules/$kversion/extra"
            if [[ -f "$gpfsmodextra/mmfs26.ko" &&  -f "$gpfsmodextra/mmfslinux.ko" && -f "$gpfsmodextra/tracedev.ko" && -f "$modulesdir/lxtrace-$kversion" ]]; then
                echo "GPFS modules mmfs26.ko, mmfslinux.ko and tracedev.ko found in volumeMount, copying to /lib/modules"
                rsync -av $modulesdir/lib/modules/$kversion /lib/modules > /dev/null
                cp -f $modulesdir/lxtrace-$kversion /usr/lpp/mmfs/bin/
                exit
            fi
        fi
        echo "Make module dir for gpfs build"
        mkdir -p "$modulesdir"
        touch "$modulesdir/building"
    fi

    # Compare only ID and major version
    if [[ "$HOST_ID" == "$CONTAINER_ID" && "$HOST_MAJOR" == "$CONTAINER_MAJOR" ]]; then
        echo "Major OS matches."
        kversion=$(uname -r)
        ln -s -T /host/usr/src/kernels/$kversion /usr/src/kernels/$kversion
        cp -rf /host/lib/modules/$kversion /lib/modules/$kversion
        mmbuildgpl || error_exit "mmbuildgpl failed"
    else
        echo "Major OS mismatch detected! Using chroot to build gpfs module"

        # get the kernel version
        kversion=$(uname -r)
        # this need for Ubuntu
        mkdir -p /usr/src/kernels
        for dir in /host/usr/src/linux-*${kversion%-*}*; do
          if [ -d "$dir" ]; then
            echo "Copying directories: $dir to /usr/src/kernels"
            rsync -a "$dir" "/usr/src/kernels/"
          fi
        done

        # create chroot directory
        mkdir -p "$CHROOT_PATH"

        # rsync /host/usr and etc to chroot
        rsync_dirs=("/host/usr" "/host/etc" "/bin")
        for dir in "${rsync_dirs[@]}"; do
          rsync -a "$dir" "$CHROOT_PATH"
        done
        rsync -a "/usr/src/kernels" "$CHROOT_PATH/usr/src"
        rsync -a "/usr/lpp" "$CHROOT_PATH/usr"

        # create symlinks for lib and lib64 inside of chroot
        cd "$CHROOT_PATH"
        ln -sfn usr/lib "$CHROOT_PATH/lib"
        ln -sfn usr/lib64 "$CHROOT_PATH/lib64"

        # mounting virtual filesystem
        mount_dirs=("dev" "proc" "sys")
        for mnt in "${mount_dirs[@]}"; do
          mkdir -p "$CHROOT_PATH/$mnt"
          mount --bind "/host/$mnt" "$CHROOT_PATH/$mnt"
        done

        # save OS name for chroot
        echo "$HOST_ID" > $CHROOT_PATH/host_id

        # add installation requirement for ubuntu
        if [[ $HOST_ID == "ubuntu" ]]; then
          prepare_ubuntu_pkgs_installation
        fi

        # entering chroot
        chroot "$CHROOT_PATH" /bin/bash -c '
          HOST_ID=$(cat ./host_id)
          cd /usr/lpp/mmfs/src
          if [[ $HOST_ID == "ubuntu" ]]; then
            export DEBIAN_FRONTEND=noninteractive
            apt update >/dev/null 2>&1
            for pkg in debconf linux-headers-$(uname -r) build-essential; do
              if ! dpkg -s "$pkg" >/dev/null 2>&1; then
                echo "Installing package: $pkg"
                apt install -y --no-install-recommends \
                    --option=Dpkg::Options::='--force-confdef' \
                    --option=Dpkg::Options::='--force-confold' \
                    "$pkg" >/dev/null 2>&1
              else
                echo "Package $pkg is already installed"
              fi
            done
            config/configure linuxdistribution=UBUNTU_LINUX
          else
            config/configure linuxdistribution=REDHAT_AS_LINUX
          fi
          if command -v mmbuildgpl >/dev/null 2>&1 && mmbuildgpl; then
            echo "mmbuildgpl succeeded"
          else
            echo "mmbuildgpl unavailable or failed; falling back to make..."
            make World || error_exit "make World failed"
            make InstallImages || error_exit "make InstallImages failed"
          fi
        '  || error_exit "chroot build failed"

        # unmount dev/ptrs for ubuntu
        if [[ $HOST_ID == "ubuntu" ]]; then
          umount "$CHROOT_PATH/dev/pts"
        fi

        # clean up and unmount
        for mnt in "${mount_dirs[@]}"; do
          umount "$CHROOT_PATH/$mnt"
        done

        # get the modules from chroot
        kversion=$(uname -r)
        rm -rf /lib/modules/$kversion
        rsync -av /opt/chroot/usr/lib/modules/$kversion /lib/modules >/dev/null
        cp -f /opt/chroot/usr/lpp/mmfs/bin/lxtrace-$kversion /usr/lpp/mmfs/bin/ || error_exit "Failed to copy lxtrace binary"
    fi
    if [[ -d "/var/mmfs/gpfsmodules" ]]; then
        echo "Copy built modules to PVC volume mount"
        mkdir -p $modulesdir/lib/modules
        rsync -av /lib/modules/$kversion "$modulesdir/lib/modules/" >/dev/null
        cp -f /usr/lpp/mmfs/bin/lxtrace-$kversion "$modulesdir/lxtrace-$kversion"
        rm -f "$modulesdir/building"
    fi
    echo "GPFS modules are built successfully"
  hostPathDirectories: |
    /run/mellanox/drivers
    /
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: buildgpl
  namespace: ibm-spectrum-scale
